# Generated by Django 4.1.7 on 2023-03-07 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100, null=True)),
                ('identification', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bloodgroup', models.CharField(max_length=3)),
                ('dob', models.DateField()),
                ('location', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('disease', models.CharField(default='none', max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('eligibility', models.BooleanField(default=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
