# Generated by Django 4.1.7 on 2023-03-07 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_eligibility_donor_eligibile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
