# Generated by Django 4.1.7 on 2023-03-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='identification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
