# Generated by Django 4.1.7 on 2023-03-12 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_remove_stock_unit_stock_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='status',
        ),
    ]
