# Generated by Django 4.1.7 on 2023-03-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_remove_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
